apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: flask-fruits-app
  namespace: demo-user2
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/raphaelmorsch/openshift-virtualization-demo.git'
      ref: main
    contextDir: flask-app
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'flask-fruits-app:latest'
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: git-webhook-secret
