apiVersion: v1
kind: Service
metadata:
  name: postgres-vm-service
  namespace: demo-user2
spec:
  selector:
    kubevirt.io/domain: fedora-postgres-vm
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
