apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-postgres-vm
  namespace: demo-user2
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres-vm
    app.kubernetes.io/part-of: fruit-crud-app
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora-postgres-vm
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
      volumes:
        - name: rootdisk
          dataVolume:
            name: fedora-dv
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: fedora-postgres-vm
              ssh_pwauth: True
              users:
                - name: fedora
                  groups: wheel
                  shell: /bin/bash
                  sudo: ["ALL=(ALL) NOPASSWD:ALL"]
                  lock_passwd: false
                  passwd: $2y$10$SHXEFhiHvgF0jNUGK9i6Du.D8TaeGwjXnc4JCB7qFo.TC70WMlMYu
              runcmd:
                - dnf install -y postgresql-server postgresql firewalld
                - systemctl enable firewalld
                - systemctl start firewalld
                - postgresql-setup --initdb
                - systemctl enable postgresql
                - systemctl start postgresql
                - sudo -u postgres psql -c "CREATE DATABASE fruits;"
                - sudo -u postgres psql -d fruits -c "CREATE TABLE fruits (id SERIAL PRIMARY KEY, name VARCHAR(50), country_of_origin VARCHAR(50), taste VARCHAR(10), season_period VARCHAR(50));"
                - echo "host all all 0.0.0.0/0 trust" >> /var/lib/pgsql/data/pg_hba.conf
                - echo "listen_addresses='*'" >> /var/lib/pgsql/data/postgresql.conf
                - systemctl restart postgresql
                - firewall-cmd --add-port=5432/tcp --permanent
                - firewall-cmd --reload
