apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virtualization-vm
  namespace: demo-user2
spec:
  project: default
  source:
    repoURL: 'https://github.com/raphaelmorsch/openshift-virtualization-demo.git'
    targetRevision: HEAD
    path: base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-user2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
